<?php

use Livewire\Volt\Component;
use App\Models\Product;
use App\Models\PurchaseOrder;
use App\Models\PurchaseOrderItem;
use App\Models\Supplier;
use App\Models\InventoryTransaction;
use App\Models\BinProductStock;
use Illuminate\Support\Facades\Auth;

new class extends Component {
    public $suggestions = [];
    public $safetyFactor = 1.10; // 10% safety stock default
    
    public function mount()
    {
        $this->loadSuggestions();
    }
    
    public function loadSuggestions()
    {
        // Load all active products with suppliers
        $this->suggestions = Product::whereNotNull('velocity')
            ->where('velocity', '>', 0)
            ->with('suppliers')
            ->get()
            ->map(function($product) {
                // Calculate stock
                $in = InventoryTransaction::where('product_id', $product->id)->where('type', 'in')->sum('quantity');
                $out = InventoryTransaction::where('product_id', $product->id)->where('type', 'out')->sum('quantity');
                $product->current_stock = max($in - $out, 0);

                // Compute simulated reorder level on the fly
                $leadTime = $product->lead_time_days ?? 7;
                $product->simulated_reorder_level = (int)ceil(($product->velocity * $leadTime) * $this->safetyFactor);

                // Calculate days until stockout
                $product->days_until_stockout = $product->velocity > 0 
                    ? ($product->current_stock / $product->velocity) 
                    : 999;

                return $product;
            })
            ->filter(function($product) {
                // Filter only products near/below reorder point
                // Local dev matches all for visibility
                if (env('APP_ENV') === 'local') return true;
                return $product->current_stock <= $product->simulated_reorder_level;
            });
    }

    public function updatedSafetyFactor()
    {
        $this->loadSuggestions();
    }
    
    public function applySafetyLevels()
    {
        if (!Auth::user()->can('manage manufacturing')) {
            abort(403);
        }

        $products = Product::whereNotNull('velocity')->where('velocity', '>', 0)->get();
        foreach ($products as $product) {
            $leadTime = $product->lead_time_days ?? 7;
            $dynamicReorderLevel = (int)ceil(($product->velocity * $leadTime) * $this->safetyFactor);
            $product->update([
                'dynamic_reorder_level' => $dynamicReorderLevel,
            ]);
        }
        
        $this->loadSuggestions();
        $this->dispatch('toast', type: 'success', message: 'Safety stock configurations saved successfully.');
    }
    
    public function generatePO($productId)
    {
        if (!Auth::user()->can('create purchase_orders')) {
            abort(403);
        }

        $product = Product::with('suppliers')->find($productId);
        if(!$product) return;
        
        $supplier = $product->suppliers->first(); // Get primary supplier
        if(!$supplier) {
            $this->dispatch('toast', type: 'error', message: 'No supplier linked to this product.');
            return;
        }
        
        $leadTime = $product->lead_time_days ?? 7;
        $reorderLevel = (int)ceil(($product->velocity * $leadTime) * $this->safetyFactor);
        $orderQty = max($reorderLevel * 2, 50); // Order enough for 2 cycles
        
        $po = PurchaseOrder::create([
            'supplier_id' => $supplier->id,
            'status' => 'draft',
            'approval_status' => 'pending_approval',
            'total_amount' => 0,
            'subtotal' => 0,
            'gst_amount' => 0,
            'remarks' => 'Auto-generated by AI Forecasting',
        ]);
        
        $price = $supplier->pivot ? $supplier->pivot->price : $product->cost_price;
        
        $po->items()->create([
            'product_id' => $product->id,
            'quantity' => $orderQty,
            'unit_price' => $price,
        ]);
        
        $po->update([
            'subtotal' => $orderQty * $price,
            'total_amount' => $orderQty * $price,
        ]);
        
        $this->dispatch('toast', type: 'success', message: 'PO #'.$po->id.' generated automatically by AI.');
        $this->loadSuggestions();
    }

    public function bulkGeneratePOs()
    {
        if (!Auth::user()->can('create purchase_orders')) {
            abort(403);
        }

        $replenishItems = $this->suggestions->filter(function($product) {
            return $product->current_stock <= $product->simulated_reorder_level;
        });

        if ($replenishItems->isEmpty()) {
            $this->dispatch('toast', type: 'info', message: 'All inventory levels are optimal for the current safety factor.');
            return;
        }

        $supplierGroups = [];
        foreach ($replenishItems as $product) {
            $supplier = $product->suppliers->first();
            if ($supplier) {
                $supplierGroups[$supplier->id][] = $product;
            }
        }

        if (empty($supplierGroups)) {
            $this->dispatch('toast', type: 'error', message: 'No suppliers are linked to below-safety products.');
            return;
        }

        $poCount = 0;
        foreach ($supplierGroups as $supplierId => $items) {
            $supplier = Supplier::find($supplierId);
            $po = PurchaseOrder::create([
                'supplier_id' => $supplier->id,
                'status' => 'draft',
                'approval_status' => 'pending_approval',
                'total_amount' => 0,
                'subtotal' => 0,
                'gst_amount' => 0,
                'remarks' => 'Bulk AI Replenishment (Safety factor ' . number_format($this->safetyFactor, 2) . ')',
            ]);

            $totalAmount = 0;
            foreach ($items as $product) {
                $orderQty = max($product->simulated_reorder_level * 2, 50);
                $price = $supplier->pivot ? $supplier->pivot->price : $product->cost_price;
                $po->items()->create([
                    'product_id' => $product->id,
                    'quantity' => $orderQty,
                    'unit_price' => $price,
                ]);
                $totalAmount += ($orderQty * $price);
            }

            $po->update([
                'subtotal' => $totalAmount,
                'total_amount' => $totalAmount,
            ]);
            $poCount++;
        }

        $this->loadSuggestions();
        $this->dispatch('toast', type: 'success', message: "Successfully generated {$poCount} draft Purchase Orders.");
    }
    
    public function recalculate()
    {
        \Illuminate\Support\Facades\Artisan::call('demand:calculate');
        $this->loadSuggestions();
        $this->dispatch('toast', type: 'success', message: 'AI Forecasts updated based on latest 30-day velocity.');
    }

    public function getSvgPath($product)
    {
        $currentStock = $product->current_stock;
        $points = [];
        $tempStock = $currentStock + ($product->velocity * 15); // Stock levels 15 days ago
        
        for ($i = 0; $i < 10; $i++) {
            $tempStock -= ($product->velocity * 3);
            $points[] = max($tempStock, 0);
        }

        $maxVal = max(max($points), 10);
        $svgPoints = [];
        foreach ($points as $xIndex => $val) {
            $x = $xIndex * 13;
            $y = 40 - (($val / $maxVal) * 32); // margin of 8px
            $svgPoints[] = "{$x},{$y}";
        }
        return implode(' ', $svgPoints);
    }
}; ?>

<div class="max-w-7xl mx-auto sm:px-6 lg:px-8 py-8 space-y-6">
    
    <!-- Title Section -->
    <div class="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
            <h2 class="text-3xl font-black text-gray-900 flex items-center gap-2">
                <svg class="w-8 h-8 text-indigo-600 animate-pulse" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 10V3L4 14h7v7l9-11h-7z"/></svg>
                AI Demand Forecasting
            </h2>
            <p class="text-gray-500 mt-1 text-sm">Automated demand modeling based on 30-day consumption velocity and lead times.</p>
        </div>
        <div class="flex items-center gap-3">
            <button wire:click="recalculate" class="bg-white border border-slate-200 hover:bg-slate-50 text-slate-700 font-bold py-2.5 px-4 rounded-xl shadow-sm flex items-center gap-2 text-sm transition">
                <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 4v5h.582m15.356 2A8.001 8.001 0 004.582 9m0 0H9m11 11v-5h-.581m0 0a8.003 8.003 0 01-15.357-2m15.357 2H15"/></svg>
                Recalculate Base
            </button>
            @can('create purchase_orders')
            <button wire:click="bulkGeneratePOs" class="bg-indigo-600 hover:bg-indigo-700 text-white font-bold py-2.5 px-5 rounded-xl shadow-md hover:shadow-indigo-600/20 text-sm flex items-center gap-2 transition">
                Bulk Auto-Generate POs
            </button>
            @endcan
        </div>
    </div>

    <!-- Interactive Simulation Header Panel -->
    <div class="bg-white p-6 rounded-2xl border border-slate-200 shadow-sm grid grid-cols-1 md:grid-cols-3 gap-6 items-center">
        <div class="md:col-span-2">
            <label class="block text-xs font-black text-slate-400 uppercase tracking-wider mb-2">Simulate Safety Stock Multiplier</label>
            <div class="flex items-center gap-4">
                <input type="range" min="1.0" max="2.0" step="0.05" wire:model.live="safetyFactor" class="w-full h-2 bg-slate-200 rounded-lg appearance-none cursor-pointer accent-indigo-600">
                <span class="text-lg font-black text-indigo-700 w-16 text-right">{{ number_format($this->safetyFactor * 100) }}%</span>
            </div>
            <p class="text-xs text-slate-400 mt-2">Adjust safety thresholds to buffer against vendor lead-time volatility and seasonal demand spikes.</p>
        </div>
        <div class="text-right">
            <button wire:click="applySafetyLevels" class="w-full md:w-auto px-5 py-2.5 bg-slate-900 hover:bg-black text-white font-bold rounded-xl text-xs shadow-md transition">
                Apply Safety Settings to DB
            </button>
        </div>
    </div>
    
    <!-- Suggestions Grid -->
    <div class="grid grid-cols-1 md:grid-cols-2 gap-6">
        @forelse($suggestions as $product)
            <div class="bg-white rounded-2xl shadow-sm border border-slate-200 p-6 flex flex-col justify-between gap-5 relative overflow-hidden group">
                
                <!-- Risk Gradient Border Highlight -->
                @if($product->days_until_stockout <= 5)
                    <div class="absolute left-0 top-0 bottom-0 w-1.5 bg-rose-500"></div>
                @elseif($product->days_until_stockout <= 15)
                    <div class="absolute left-0 top-0 bottom-0 w-1.5 bg-amber-500"></div>
                @else
                    <div class="absolute left-0 top-0 bottom-0 w-1.5 bg-emerald-500"></div>
                @endif

                <div class="flex justify-between items-start gap-4">
                    <div class="flex gap-4">
                        <div class="w-12 h-12 rounded-xl bg-slate-50 flex items-center justify-center border border-slate-200 shadow-sm text-indigo-600 font-black text-lg">
                            {{ substr($product->name, 0, 1) }}
                        </div>
                        <div>
                            <h3 class="text-base font-black text-slate-800 tracking-tight">{{ $product->name }}</h3>
                            <span class="text-[10px] font-mono text-slate-400 uppercase tracking-wider block mt-0.5">{{ $product->sku }}</span>
                        </div>
                    </div>
                    
                    <!-- Stockout Status Badge -->
                    <div>
                        @if($product->days_until_stockout <= 5)
                            <span class="px-2.5 py-1 rounded-lg text-[10px] font-bold bg-rose-50 text-rose-700 border border-rose-200">Stockout Risk ({{ number_format($product->days_until_stockout, 1) }}d)</span>
                        @elseif($product->days_until_stockout <= 15)
                            <span class="px-2.5 py-1 rounded-lg text-[10px] font-bold bg-amber-50 text-amber-700 border border-amber-200">Replenish Soon ({{ number_format($product->days_until_stockout, 1) }}d)</span>
                        @else
                            <span class="px-2.5 py-1 rounded-lg text-[10px] font-bold bg-emerald-50 text-emerald-700 border border-emerald-200">Optimal Stock ({{ number_format($product->days_until_stockout, 1) }}d)</span>
                        @endif
                    </div>
                </div>

                <!-- Mid Section details and trend chart -->
                <div class="grid grid-cols-2 gap-4 items-center border-t border-b border-slate-100 py-4">
                    <div class="space-y-3">
                        <div class="grid grid-cols-2 gap-2 text-xs">
                            <div>
                                <span class="text-slate-400 block uppercase font-bold tracking-wider text-[9px]">Velocity</span>
                                <span class="font-extrabold text-slate-700 mt-0.5 block">{{ number_format($product->velocity, 1) }}/day</span>
                            </div>
                            <div>
                                <span class="text-slate-400 block uppercase font-bold tracking-wider text-[9px]">Lead Time</span>
                                <span class="font-extrabold text-slate-700 mt-0.5 block">{{ $product->lead_time_days ?? 7 }} days</span>
                            </div>
                            <div>
                                <span class="text-slate-400 block uppercase font-bold tracking-wider text-[9px]">On Hand</span>
                                <span class="font-extrabold text-slate-700 mt-0.5 block">{{ number_format($product->current_stock, 1) }}</span>
                            </div>
                            <div>
                                <span class="text-indigo-400 block uppercase font-bold tracking-wider text-[9px]">Reorder Pt</span>
                                <span class="font-extrabold text-indigo-700 mt-0.5 block">{{ $product->simulated_reorder_level }}</span>
                            </div>
                        </div>
                    </div>
                    
                    <!-- SVG Trend chart -->
                    <div class="bg-slate-50 border border-slate-150 rounded-xl p-3 flex flex-col items-center justify-between h-20">
                        <div class="text-[9px] font-bold text-slate-400 uppercase tracking-wider">Inventory Trend (60d)</div>
                        <svg class="w-full h-8 text-indigo-500 overflow-visible" viewBox="0 0 120 40">
                            <polyline fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" points="{{ $this->getSvgPath($product) }}"></polyline>
                        </svg>
                    </div>
                </div>

                <div class="flex justify-between items-center text-xs">
                    <div class="text-slate-500">
                        @if($product->suppliers->count() > 0)
                            Supplier: <strong class="font-bold text-slate-700">{{ $product->suppliers->first()->name }}</strong>
                        @else
                            <span class="text-rose-600 font-bold">No Supplier Link!</span>
                        @endif
                    </div>
                    @can('create purchase_orders')
                    <button wire:click="generatePO({{ $product->id }})" class="bg-slate-900 hover:bg-black text-white font-bold py-2 px-4 rounded-xl shadow transition active:scale-95 text-xs flex items-center gap-1.5">
                        <svg class="w-3.5 h-3.5 text-emerald-400" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"/></svg>
                        Auto-Order
                    </button>
                    @endcan
                </div>
            </div>
        @empty
            <div class="bg-white rounded-2xl p-12 text-center shadow-sm border border-slate-200 md:col-span-2">
                <div class="w-20 h-20 bg-green-50 text-green-500 rounded-full flex items-center justify-center mx-auto mb-4">
                    <svg class="w-10 h-10" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"/></svg>
                </div>
                <h3 class="text-xl font-bold text-gray-900">Inventory is Optimal</h3>
                <p class="text-slate-500 mt-2">The AI model detects no immediate stockout risks based on current consumption velocity.</p>
            </div>
        @endforelse
    </div>
</div>
